name: Build & Deploy nestjs-app to DO

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push nest-techtst Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: doctl
          password: ${{ secrets.DO_API_TOKEN }}

      - name: Build and push nest-techtst image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/nest-techtst:latest
            registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/nest-techtst:${{ github.sha }}

  deploy:
    name: Update nestjs-app on DO App Platform
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Deploy nestjs-app
        run: |
          doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml
