name: Build & Deploy nestjs-app to DO

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push nest-techtst Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Build container image
        run: docker build -t nest-techtst:latest

      - name: Tag container image
        run: docker tag nest-techtst registry.digitalocean.com/sprbaynes-registry/nest-techtst:latest  

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/sprbaynes-registry/nest-techtst:latest

  deploy:
    name: Update nestjs-app on DO App Platform
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Deploy nestjs-app
        run: |
          doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml